version: '3.9'
services:
  zk:
    container_name: zk
    image: zookeeper:3.6.3
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=127.0.0.1:2888:3888;2181
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
      ZOO_MAX_CLIENT_CNXNS: 0
  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - 9092:9092
      - 15000:15000
    depends_on:
      - zk
    links:
      - zk:zk
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://{IP}:9092 # 必須是宿主IP
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LOG_RETENTION_HOURS: 24
      JMX_PORT: 15000
  kafka2:
    container_name: kafka2
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - 9093:9093
      - 15001:15001
    depends_on:
      - zk
    links:
      - zk:zk
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://{IP}:9093 # 必須是宿主IP
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_LOG_RETENTION_HOURS: 24
      JMX_PORT: 15001
  kafka3:
    container_name: kafka3
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - 9094:9094
      - 15002:15002
    depends_on:
      - zk
    links:
      - zk:zk
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://{IP}:9094 # 必須是宿主IP
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_LOG_RETENTION_HOURS: 24
      JMX_PORT: 15002
  kafka-management:
    container_name: kafka-management
    image: image: hlebalbau/kafka-manager:stable
    ports:
      - 9000:9000
    depends_on:
      - zk
    links:
      - zk:zk
    environment:
      ZK_HOSTS: zk:2181